FROM python

MAINTAINER fengyong fkworld@foxmail.com

WORKDIR app
VOLUME ["/app"]
COPY requirements.txt /app/
RUN python3 -m pip3 install --upgrade pip3
RUN pip3 install -r /app/requirements.txt

EXPOSE 80

CMD ["gunicorn","-w","4","-b","0.0.0.0:80","start:app"]